version: "3.9"

services:
  frontend:
    image: ghcr.io/sathyazerosoft-creator/eventsmap-frontend:test
    container_name: eventsmap-test
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env
