version: "3.9"

services:
  frontend:
    image: ghcr.io/sathyazerosoft-creator/eventsmap-frontend:latest
    container_name: eventsmap-prod
    restart: unless-stopped
    ports:
      - "3003:3000"
    env_file:
      - .env
