version: "3.9"

services:
  frontend:
    image: ghcr.io/zerosoft-technologies/eventsmap-frontend-vue:test
    container_name: eventsmap-test
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "3001:3000"
    env_file:
      - .env
