version: "3.9"

services:
  frontend:
    image: ghcr.io/sathyazerosoft-creator/eventsmap-frontend:stage
    container_name: eventsmap-stage
    restart: unless-stopped
    ports:
      - "3002:3000"
    env_file:
      - .env
